export interface SeedProfileData {
  email: string;
  phone: string;
  firstName: string;
  lastName: string;
  gender: 'MALE' | 'FEMALE';
  age: number;
  height: number;
  dob: string;
  motherTongue: string;
  religion: string;
  community: string;
  caste: string;
  city: string;
  state: string;
  educationLevel: string;
  degree: string;
  occupation: string;
  annualIncome: number;
  incomeRange: string;
  diet: 'VEGETARIAN' | 'NON_VEGETARIAN' | 'EGGETARIAN' | 'JAIN';
  about: string;
  avatar: string;
  photos: string[];
  isVerified: boolean;
  isPremium: boolean;
  familyType: 'JOINT' | 'NUCLEAR';
  fatherOccupation: string;
  motherOccupation: string;
  hobbies: string[];
  interests: string[];
}

export const SEED_PROFILES: SeedProfileData[] = [
  {
    email: 'ananya.sharma@rishta24.test',
    phone: '+919876500001',
    firstName: 'Ananya',
    lastName: 'Sharma',
    gender: 'FEMALE',
    age: 26,
    height: 165,
    dob: '1999-04-15',
    motherTongue: 'Hindi',
    religion: 'Hindu',
    community: 'Brahmin',
    caste: 'Gaur Brahmin',
    city: 'Mumbai',
    state: 'Maharashtra',
    educationLevel: 'Masters',
    degree: 'M.Tech in Computer Science',
    occupation: 'Senior Software Engineer',
    annualIncome: 24,
    incomeRange: '₹20 - 30 Lakhs',
    diet: 'VEGETARIAN',
    about: 'Warm, ambitious, and deeply connected to cultural values. Love weekend hiking, playing classical guitar, and exploring specialty cafes. Looking for an educated, caring life partner with a progressive outlook.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    photos: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    isPremium: true,
    familyType: 'NUCLEAR',
    fatherOccupation: 'Senior Executive at PSU Bank (Retd.)',
    motherOccupation: 'Professor of Literature',
    hobbies: ['Classical Music', 'Trekking', 'Reading', 'Photography'],
    interests: ['Technology', 'Travel', 'Art', 'Yoga', 'Cooking'],
  },
  {
    email: 'rohan.verma@rishta24.test',
    phone: '+919876500002',
    firstName: 'Rohan',
    lastName: 'Verma',
    gender: 'MALE',
    age: 28,
    height: 180,
    dob: '1997-08-22',
    motherTongue: 'Punjabi',
    religion: 'Hindu',
    community: 'Khatri',
    caste: 'Verma',
    city: 'Delhi NCR',
    state: 'Delhi',
    educationLevel: 'Masters',
    degree: 'MBA (Finance), IIM Lucknow',
    occupation: 'Investment Banker',
    annualIncome: 38,
    incomeRange: '₹30 - 45 Lakhs',
    diet: 'EGGETARIAN',
    about: 'Driven professional with a zest for life. Passionate about financial markets, fitness, and family get-togethers. Seeking a partner who is cheerful, intelligent, and values mutual respect.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    isPremium: true,
    familyType: 'JOINT',
    fatherOccupation: 'Business Owner (Textile Exports)',
    motherOccupation: 'Homemaker',
    hobbies: ['Tennis', 'Gym', 'Stock Trading', 'Road Trips'],
    interests: ['Economics', 'Fitness', 'Culinary Arts', 'Movies'],
  },
  {
    email: 'priya.nair@rishta24.test',
    phone: '+919876500003',
    firstName: 'Priya',
    lastName: 'Nair',
    gender: 'FEMALE',
    age: 27,
    height: 162,
    dob: '1998-11-05',
    motherTongue: 'Malayalam',
    religion: 'Hindu',
    community: 'Nair',
    caste: 'Menon',
    city: 'Bengaluru',
    state: 'Karnataka',
    educationLevel: 'Masters',
    degree: 'MD (Dermatology)',
    occupation: 'Consultant Dermatologist',
    annualIncome: 28,
    incomeRange: '₹25 - 35 Lakhs',
    diet: 'VEGETARIAN',
    about: 'Doctor by profession, artist at heart. Believe in living life with gratitude, empathy, and joy. Love traditional classical dance and contemporary interior design.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
    photos: [
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    isPremium: true,
    familyType: 'NUCLEAR',
    fatherOccupation: 'Cardiologist',
    motherOccupation: 'Architect',
    hobbies: ['Classical Dance', 'Gardening', 'Painting', 'Travel'],
    interests: ['Healthcare', 'Art', 'Wellness', 'Music'],
  },
  {
    email: 'aditya.kulkarni@rishta24.test',
    phone: '+919876500004',
    firstName: 'Aditya',
    lastName: 'Kulkarni',
    gender: 'MALE',
    age: 29,
    height: 178,
    dob: '1996-02-14',
    motherTongue: 'Marathi',
    religion: 'Hindu',
    community: 'Maratha',
    caste: 'Deshastha',
    city: 'Pune',
    state: 'Maharashtra',
    educationLevel: 'Bachelors',
    degree: 'B.Tech (Mechanical) COEP',
    occupation: 'Lead Product Manager',
    annualIncome: 32,
    incomeRange: '₹30 - 40 Lakhs',
    diet: 'VEGETARIAN',
    about: 'Product thinker working in deep-tech automotive. Love cycling around Sahyadris, reading non-fiction, and family festivals. Looking for a partner who is optimistic and kind.',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
    photos: [
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    isPremium: false,
    familyType: 'NUCLEAR',
    fatherOccupation: 'Civil Engineer (PWD Govt)',
    motherOccupation: 'School Principal (Retd.)',
    hobbies: ['Cycling', 'Astronomy', 'Reading', 'Marathons'],
    interests: ['Technology', 'Nature', 'Social Impact', 'History'],
  },
  {
    email: 'meera.iyer@rishta24.test',
    phone: '+919876500005',
    firstName: 'Meera',
    lastName: 'Iyer',
    gender: 'FEMALE',
    age: 25,
    height: 168,
    dob: '2000-09-18',
    motherTongue: 'Tamil',
    religion: 'Hindu',
    community: 'Brahmin',
    caste: 'Vadama Iyer',
    city: 'Chennai',
    state: 'Tamil Nadu',
    educationLevel: 'Masters',
    degree: 'Chartered Accountant (AIR 14)',
    occupation: 'Senior Financial Analyst',
    annualIncome: 22,
    incomeRange: '₹20 - 30 Lakhs',
    diet: 'VEGETARIAN',
    about: 'CA by profession with a love for Carnatic violin and filter coffee conversations. Family-oriented with a strong belief in shared growth and happiness.',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    photos: [
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    isPremium: true,
    familyType: 'NUCLEAR',
    fatherOccupation: 'Vice President, IT MNC',
    motherOccupation: 'Carnatic Music Teacher',
    hobbies: ['Violin', 'Baking', 'Chess', 'Podcasts'],
    interests: ['Finance', 'Culture', 'Philosophy', 'Travel'],
  },
  {
    email: 'karan.singh@rishta24.test',
    phone: '+919876500006',
    firstName: 'Karan',
    lastName: 'Singh',
    gender: 'MALE',
    age: 30,
    height: 183,
    dob: '1995-06-10',
    motherTongue: 'Punjabi',
    religion: 'Sikh',
    community: 'Jat Sikh',
    caste: 'Gill',
    city: 'Chandigarh',
    state: 'Punjab',
    educationLevel: 'Bachelors',
    degree: 'B.Sc Agriculture & Agribusiness',
    occupation: 'Agri-Tech Entrepreneur',
    annualIncome: 45,
    incomeRange: '₹40 - 60 Lakhs',
    diet: 'NON_VEGETARIAN',
    about: 'Modern organic farming innovator. Grounded in Sikh traditions and ethics. Love horses, outdoor sports, and warm family dinners.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    photos: [
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    isPremium: true,
    familyType: 'JOINT',
    fatherOccupation: 'Land Owner & Politician',
    motherOccupation: 'Homemaker',
    hobbies: ['Horse Riding', 'Shooting', 'Cooking', 'Gym'],
    interests: ['Agriculture', 'Business', 'Sports', 'Community Service'],
  },
  {
    email: 'tanvi.patel@rishta24.test',
    phone: '+919876500007',
    firstName: 'Tanvi',
    lastName: 'Patel',
    gender: 'FEMALE',
    age: 26,
    height: 160,
    dob: '1999-12-01',
    motherTongue: 'Gujarati',
    religion: 'Hindu',
    community: 'Patel',
    caste: 'Leuva Patel',
    city: 'Ahmedabad',
    state: 'Gujarat',
    educationLevel: 'Masters',
    degree: 'M.Des (UI/UX), NID Ahmedabad',
    occupation: 'Staff Product Designer',
    annualIncome: 26,
    incomeRange: '₹25 - 35 Lakhs',
    diet: 'JAIN',
    about: 'Design enthusiast who finds beauty in the little details. Love pottery, museum visits, and Gujarati delicacies. Looking for someone genuine and joyful.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    photos: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    isPremium: true,
    familyType: 'NUCLEAR',
    fatherOccupation: 'Diamond Merchant',
    motherOccupation: 'Interior Designer',
    hobbies: ['Pottery', 'Calligraphy', 'Yoga', 'Reading'],
    interests: ['Design', 'Art', 'Architecture', 'Mindfulness'],
  },
  {
    email: 'vikram.reddy@rishta24.test',
    phone: '+919876500008',
    firstName: 'Vikram',
    lastName: 'Reddy',
    gender: 'MALE',
    age: 29,
    height: 181,
    dob: '1996-07-29',
    motherTongue: 'Telugu',
    religion: 'Hindu',
    community: 'Reddy',
    caste: 'Kapu',
    city: 'Hyderabad',
    state: 'Telangana',
    educationLevel: 'Masters',
    degree: 'MS in Data Analytics (US)',
    occupation: 'Principal Data Scientist',
    annualIncome: 42,
    incomeRange: '₹40 - 55 Lakhs',
    diet: 'NON_VEGETARIAN',
    about: 'Tech professional returned from US. Love badminton, playing synthesizer, and exploring culinary wonders. Looking for a partner with strong mutual chemistry and family values.',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
    photos: [
      'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    isPremium: true,
    familyType: 'NUCLEAR',
    fatherOccupation: 'Managing Director, Infra Corp',
    motherOccupation: 'NGO Director',
    hobbies: ['Badminton', 'Electronic Music', 'Scuba Diving', 'Cooking'],
    interests: ['AI & Robotics', 'Cinema', 'Travel', 'Science'],
  },
  {
    email: 'shreya.sen@rishta24.test',
    phone: '+919876500009',
    firstName: 'Shreya',
    lastName: 'Sen',
    gender: 'FEMALE',
    age: 27,
    height: 164,
    dob: '1998-03-24',
    motherTongue: 'Bengali',
    religion: 'Hindu',
    community: 'Kayastha',
    caste: 'Sen',
    city: 'Kolkata',
    state: 'West Bengal',
    educationLevel: 'Masters',
    degree: 'MA in Comparative Literature, Jadavpur University',
    occupation: 'Senior Content Strategist & Author',
    annualIncome: 18,
    incomeRange: '₹15 - 25 Lakhs',
    diet: 'NON_VEGETARIAN',
    about: 'Avid bibliophile, amateur poet, and film enthusiast. Cherish deep conversations over Darjeeling tea. Looking for a progressive and open-minded life partner.',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
    photos: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    isPremium: false,
    familyType: 'NUCLEAR',
    fatherOccupation: 'Professor of Economics',
    motherOccupation: 'Rabindra Sangeet Vocalist',
    hobbies: ['Poetry', 'Vintage Films', 'Theater', 'Coffee Brewing'],
    interests: ['Literature', 'Cinema', 'World Cultures', 'Travel'],
  },
  {
    email: 'rahul.agarwal@rishta24.test',
    phone: '+919876500010',
    firstName: 'Rahul',
    lastName: 'Agarwal',
    gender: 'MALE',
    age: 28,
    height: 175,
    dob: '1997-10-12',
    motherTongue: 'Hindi',
    religion: 'Hindu',
    community: 'Agarwal',
    caste: 'Baniya',
    city: 'Jaipur',
    state: 'Rajasthan',
    educationLevel: 'Masters',
    degree: 'B.Tech + MBA (NMIMS Mumbai)',
    occupation: 'Co-Founder & CEO, D2C Brand',
    annualIncome: 50,
    incomeRange: '₹50 - 75 Lakhs',
    diet: 'VEGETARIAN',
    about: 'Energetic startup founder who values traditional heritage alongside modern lifestyle. Love squash, royal heritage architecture, and family celebrations.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    photos: [
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    isPremium: true,
    familyType: 'JOINT',
    fatherOccupation: 'Industrialist',
    motherOccupation: 'Homemaker',
    hobbies: ['Squash', 'Heritage Travel', 'Fine Dining', 'Podcasts'],
    interests: ['Entrepreneurship', 'E-Commerce', 'Brand Building', 'Culture'],
  },
];
