import { z } from 'zod';

export const updateProfileSchema = z.object({
  firstName: z.string().min(2).optional(),
  lastName: z.string().min(1).optional(),
  height: z.number().min(100).max(250).optional(),
  maritalStatus: z.enum(['NEVER_MARRIED', 'DIVORCED', 'WIDOWED', 'AWAITING_DIVORCE']).optional(),
  religion: z.string().optional(),
  community: z.string().optional(),
  caste: z.string().optional(),
  subCaste: z.string().optional(),
  gotra: z.string().optional(),
  manglik: z.enum(['NO', 'YES', 'DO_NOT_KNOW', 'ANSHIK']).optional(),
  about: z.string().max(2000).optional(),
  
  city: z.string().optional(),
  state: z.string().optional(),
  country: z.string().optional(),
  citizenship: z.string().optional(),
  
  educationLevel: z.string().optional(),
  degree: z.string().optional(),
  college: z.string().optional(),
  occupation: z.string().optional(),
  employer: z.string().optional(),
  annualIncome: z.number().optional(),
  incomeRange: z.string().optional(),
  
  familyType: z.enum(['JOINT', 'NUCLEAR']).optional(),
  fatherOccupation: z.string().optional(),
  motherOccupation: z.string().optional(),
  brothersCount: z.number().min(0).optional(),
  sistersCount: z.number().min(0).optional(),
  familyValues: z.enum(['TRADITIONAL', 'MODERATE', 'LIBERAL']).optional(),
  familyLocation: z.string().optional(),
  
  diet: z.enum(['VEGETARIAN', 'NON_VEGETARIAN', 'EGGETARIAN', 'JAIN', 'VEGAN']).optional(),
  smoking: z.enum(['NO', 'OCCASIONALLY', 'YES']).optional(),
  drinking: z.enum(['NO', 'OCCASIONALLY', 'YES']).optional(),
  hobbies: z.array(z.string()).optional(),
  interests: z.array(z.string()).optional(),
  
  avatar: z.string().url().optional(),
  
  partnerPreferences: z.object({
    minAge: z.number().optional(),
    maxAge: z.number().optional(),
    minHeight: z.number().optional(),
    maxHeight: z.number().optional(),
    maritalStatus: z.array(z.string()).optional(),
    religions: z.array(z.string()).optional(),
    communities: z.array(z.string()).optional(),
    motherTongues: z.array(z.string()).optional(),
    educations: z.array(z.string()).optional(),
    occupations: z.array(z.string()).optional(),
    minIncome: z.number().optional(),
    diets: z.array(z.string()).optional(),
    states: z.array(z.string()).optional(),
    countries: z.array(z.string()).optional(),
  }).optional(),
  
  privacySettings: z.object({
    profileVisibility: z.enum(['PUBLIC', 'REGISTERED_ONLY', 'MUTUAL_MATCH_ONLY']).optional(),
    phoneVisibility: z.enum(['PUBLIC', 'PREMIUM_ONLY', 'UPON_REQUEST', 'PRIVATE']).optional(),
    emailVisibility: z.enum(['PUBLIC', 'PREMIUM_ONLY', 'UPON_REQUEST', 'PRIVATE']).optional(),
    photoVisibility: z.enum(['PUBLIC', 'REGISTERED_ONLY', 'UPON_REQUEST', 'PRIVATE']).optional(),
    showOnlineStatus: z.boolean().optional(),
    showLastSeen: z.boolean().optional(),
    allowSearchEngines: z.boolean().optional(),
    incognitoMode: z.boolean().optional(),
  }).optional(),
  
  notificationSettings: z.object({
    emailAlerts: z.boolean().optional(),
    pushAlerts: z.boolean().optional(),
    smsAlerts: z.boolean().optional(),
    interestReceived: z.boolean().optional(),
    interestAccepted: z.boolean().optional(),
    messages: z.boolean().optional(),
    profileViewed: z.boolean().optional(),
    matchesRecommended: z.boolean().optional(),
    promotions: z.boolean().optional(),
  }).optional(),
});
